# -*- coding: utf-8 -*-
"""Zomato_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zpvtm7aK0JR6FetZxQ_VdfoTEdJXXMxY

# **Importing the Libraries & Loading the Data**
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

df = pd.read_csv("Zomato_data.csv")
df

"""# **DATA CLEANING**

As we know the rating of the restaurants are out of 5 only. So let's convert the data type of rate columns (From 4.1/5 - to 4.1 Only)
"""

def handle_rating(rate):
    if isinstance(rate, str):
        rate = rate.split("/")[0]
    return float(rate)

df["rate"] = df["rate"].apply(handle_rating)
df

df.info()

"""**From here we'll move with the data as per the questions we have.**

# 1. What type of restaurant do the majority of customers order from ?
"""

df.head()

sns.countplot(x=df['listed_in(type)'])
plt.xlabel("Type of Restaurant")

"""**Conclusion**

SO this concludes that majority of customers order from 'Dining' type of restaurant, followed up by 'Cafes', then 'other' and closely followed by 'Buffet'.

# 2. How many votes has each type of restaurant received from customers ?
"""

df.head()

df.groupby("listed_in(type)")["votes"].sum()

grouped_data = df.groupby("listed_in(type)")["votes"].sum()
result = pd.DataFrame({'vote':grouped_data})
plt.plot(result, c='blue', marker="o")
plt.xlabel("Type of Restaurant", c="red", size=20)
plt.ylabel("Total Votes", c="red", size=20)

"""**Conclusion**

Diningd restaurant have max votes compared to others

# **3. What are rating that the majority of restaurants have received ?**
"""

df.head()

plt.hist(df['rate'],bins =10)
plt.title('Rating Distribution')
plt.xlabel('Rating')
plt.show()

"""**Conclusion**

Majority rating received are between 3.5 - 4

# **4. Zomato has observed that most couples order most of their food online. What is their average spending on each other?**
"""

df.head()

coupled_data = df['approx_cost(for two people)']
sns.countplot(x=coupled_data)

"""**Conclusion**

So majority customers prefer to order food from 300 - 500, out of which 300 being the most order value.

# **5. Which mode (Online / Offline) has received the maximum rating?**
"""

df.head(10)

plt.figure(figsize = (6,6))
sns.boxplot(x='online_order', y='rate', data=df)

"""**Conclusion**

Online order received more rating compared to offline ratings.

# **6. Which type of restaurant received more offline orders, so that Zomato can provide customers with some good offers?**
"""

pivot_table = df.pivot_table(index='listed_in(type)', columns='online_order',aggfunc='size', fill_value=0)
sns.heatmap(pivot_table, annot=True, cmap='YlGnBu', fmt='d')
plt.title('Heatmap')
plt.xlabel('Online Order')
plt.ylabel('Type of Restaurant')
plt.show()

"""**Conclusion**

Dining restaurants receive more offline orders/customers, whereas cafes receive more online orders than offline visits.
"""